#include "hal_data.h"
#include "uart_console.h"
#include "i2c_master.h"
#include "i2c_slave.h"
#include "i2c_slave2.h"

// 宣告系統滴答計數器 (毫秒)
extern volatile uint32_t g_system_ticks;

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */

    // 1. 初始化 LED 引腳與狀態 (寫入 Low)
    led_init();

    // 2. 初始化雙 UART 控制台 (開啟硬體驅動、註冊接收緩衝)
    uart_console_init();

    // 3. 初始化 I2C Master0、Slave1 與 Slave2 驅動模組
    i2c_master_init();
    i2c_slave_init();
    i2c_slave2_init();

    // 4. 在兩個控制台上印出連線成功歡迎詞與說明
    uart_console_print(&g_console_master, "\r\n*** RA6M5 Master Console (UART9) Online ***\r\n");
    uart_console_print(&g_console_master, "Pins: TX=P109, RX=P110 | Baudrate: 115200\r\n");
    uart_console_print(&g_console_master, "Type 'help' or '?' to list available commands.\r\n\r\n");

    uart_console_print(&g_console_slave, "\r\n*** RA6M5 Slave Console (UART8) Online ***\r\n");
    uart_console_print(&g_console_slave, "Pins: TX=P105, RX=P104 | Baudrate: 115200\r\n");
    uart_console_print(&g_console_slave, "Type 'help' or '?' to list available commands.\r\n\r\n");

    uint32_t last_heartbeat_tick = 0;

    while (1)
    {
        // A. 處理 UART9 的 RX 指令解析 (Master)
        uart_console_process_rx(&g_console_master, "MASTER");

        // B. 處理 UART8 的 RX 指令解析 (Slave)
        uart_console_process_rx(&g_console_slave, "SLAVE");

        // C. 輪詢處理 I2C Slave1 與 Slave2 接收佇列/封包與日誌解析
        i2c_slave_process();
        i2c_slave2_process();

        // D. 處理 LED 閃爍與狀態翻轉邏輯
        led_process();

        // E. 驗證發送：每 60000ms (1 分鐘) 發送一次心跳資訊至兩個控制台
        if (g_system_ticks - last_heartbeat_tick >= 60000)
        {
            last_heartbeat_tick = g_system_ticks;
            uart_console_print(&g_console_master, "[Master HB] Ticks: %lu ms\r\n", g_system_ticks);
            uart_console_print(&g_console_slave, "[Slave HB] Ticks: %lu ms\r\n", g_system_ticks);
        }

        // F. 協作式 1 毫秒延遲，用以推動系統滴答計數
        R_BSP_SoftwareDelay(1, BSP_DELAY_UNITS_MILLISECONDS);
        g_system_ticks++;
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}


